### ISSUE TITLE
Blocking programatically

### ISSUE THREAD

**Issue by KabluBR** [koa-health/horizontal_blocked_scroll_physics#2]
This plugin is also blocking programatically jump to other pages... that would be no need for pageviews if its not able to move right?

**Comment by robertohuertasm** [comment]
Sorry @KabluBR but I'm not sure to understand what you mean. Could you elaborate?

**Comment by KabluBR** [comment]
My fault, lol...

The thing is... when you configure to swipe only to one side, you cannot move to the opposite side programmatically.
So for an example, if you turn off swiping to the left, you cannot navigate by commands like "pageController.nextPage".
I was thinking on using it to not allow user to swipe to the next screen, but can swipe back to previous.

👍 Thanks!!!

**Comment by tsimbalar** [comment]
@KabluBR not sure if this will be helpful to you but ... 

We've had a similar requirement when using [`carousel_slider`](https://pub.dev/packages/carousel_slider) which I assume is pretty much a wrapper on top of `PageView` / `PageController` etc.

We do use `LeftBlockedScrollPhysics`and `RightBlockedScrollPhysics` there, but what we do is that when we need to "scroll anyway" (in our case, we disallow swiping, but a button on the page allows to "go to next" anyway), we temporarily set the `ScrollPhysics` to a `AlwaysScrollableScrollPhysics` until the next page, and set it back to a "blocked" scroll once we are done moving.

I hope this helps a bit :P

**Comment by KabluBR** [comment]
Thank you for the answer! It is a good idea, I just don`t know how to change physics from inside a page of the pageview.

**Comment by robertohuertasm** [comment]
@KabluBR, @tsimbalar approach is the way to go. In order to manage this from the pages of your `PageView` you'll need to be able to conditionally rebuild the PageView. One option would be to use a StreamBuilder, and have a way to manage the stream from your pages (via blocs or by simply exposing the stream).

**Comment by petro-i** [comment]
what is the problem to use simple callback in form of predicate? if no permission - not to scroll - do not update scroll result in calculations of the scroll physics - simple )

**Comment by petro-i** [comment]
something like this:

```
double applyBoundaryConditions(ScrollMetrics position, double value) {
    final axisDirection =
        (position.pixels <= value) ? AxisDirection.up : AxisDirection.down;
    if (!predicate(axisDirection)) {
      return value - position.pixels;
    }

    return super.applyBoundaryConditions(position, value);
  }
```
