### ISSUE TITLE
Request : remove dependency to `pedantic`

### ISSUE THREAD

**Issue by tsimbalar** [koa-health/horizontal_blocked_scroll_physics#8]
The `pedantic` library is considered **deprecated** : see https://github.com/google/pedantic#readme .

There are migration instructions here : https://github.com/dart-lang/lints#migrating-from-packagepedantic .

`unawaited` is now available natively as part of `dart:async` so we could maybe rely on it instead, and remove the `pedantic` dependency all together ?

Thanks !

**Comment by robertohuertasm** [comment]
Thanks @tsimbalar! Good to know! Happy to receive a PR is someone is up to the task! Adding `Good first issue` label just in case want to tackle this.

**Comment by tsimbalar** [comment]
here you go : 
- https://github.com/koa-health/horizontal_blocked_scroll_physics/pull/9
